-- Execute as postgres with a transaction. All fixtures are rolled back.
begin;
insert into public.companies(id,name) values('bb000000-0000-4000-8000-000000000001','TEST BB Workflow'),('bb000000-0000-4000-8000-000000000002','TEST BB Isolation');
insert into auth.users(id,email) values('bb000000-0000-4000-8000-000000000011','bb-owner-test@example.invalid'),('bb000000-0000-4000-8000-000000000012','bb-employee-test@example.invalid');
insert into public.profiles(id,company_id,full_name,username,role) values('bb000000-0000-4000-8000-000000000011','bb000000-0000-4000-8000-000000000001','TEST Owner','test_bb_owner_workflow','owner'),('bb000000-0000-4000-8000-000000000012','bb000000-0000-4000-8000-000000000001','TEST Employee','test_bb_employee_workflow','employee');
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"bb000000-0000-4000-8000-000000000011","role":"authenticated"}',true);
do $$
declare eid uuid; sid uuid; cid uuid:='bb000000-0000-4000-8000-000000000001'; pid uuid; peid uuid; component uuid; stamp timestamptz; body jsonb; blocked boolean; actual numeric;
begin
  blocked:=false;
  begin perform public.generate_payroll('2099-01-01','2099-01-31','2099-01-31'); exception when raise_exception then blocked:=true; end;
  assert blocked,'Empty payroll must fail';
  assert (select count(*) from public.payroll_periods)=0,'Failed payroll must leave no period';
  body:=jsonb_build_object('employee_code','TEST-001','full_name','TEST Employee','employment_type','Tetap Permanen','onboarding_status','draft','is_active',false,'base_salary',5000000,'personal_data',jsonb_build_object('birth_place','TEST City'));
  eid:=public.save_employee(body);
  assert (select not is_active and onboarding_status='draft' from public.employees where id=eid),'Draft must be inactive';
  assert (select personal_data->>'birth_place' from public.employees where id=eid)='TEST City','Personal data persists';
  insert into public.work_schedules(company_id,name,start_time,end_time) values(cid,'TEST Schedule','08:00','17:00') returning id into sid;
  select updated_at into stamp from public.employees where id=eid;
  body:=body||jsonb_build_object('onboarding_status','complete','is_active',true,'hire_date','2098-01-01','department','TEST Department','position','TEST Position','schedule_id',sid,'profile_id','bb000000-0000-4000-8000-000000000012');
  perform public.save_employee(body,eid,stamp);
  assert (select schedule_id from public.employee_schedules where employee_id=eid)=sid,'Schedule saves atomically';
  blocked:=false;
  begin perform public.save_employee(body,eid,'2000-01-01'); exception when raise_exception then blocked:=true; end;
  assert blocked,'Stale edit must fail';
  insert into public.payroll_components(company_id,name,kind) values(cid,'TEST Allowance','earning') returning id into component;
  insert into public.employee_compensation(company_id,employee_id,component_id,amount,effective_from) values(cid,eid,component,500000,'2099-01-01');
  insert into public.employee_compensation(company_id,employee_id,component_id,amount,effective_from) values(cid,eid,component,900000,'2100-01-01');
  pid:=public.generate_payroll('2099-01-01','2099-01-31','2099-01-31');
  select id,net_pay into peid,actual from public.payroll_entries where payroll_period_id=pid;
  assert actual=5500000,'Future compensation must be excluded';
  blocked:=false;
  begin perform public.generate_payroll('2099-01-15','2099-02-14','2099-02-14'); exception when raise_exception then blocked:=true; end;
  assert blocked,'Overlapping period must fail';
  perform public.adjust_payroll_entry(peid,5000000,'[{"name":"Bonus","kind":"earning","amount":500000},{"name":"Potongan","kind":"deduction","amount":100000}]');
  assert (select total_net from public.payroll_periods where id=pid)=5400000,'Adjustment updates totals';
  blocked:=false;
  begin update public.payroll_periods set status='paid' where id=pid; exception when raise_exception then blocked:=true; end;
  assert blocked,'Status cannot skip review';
  update public.payroll_periods set status='review' where id=pid;
  update public.payroll_periods set status='approved' where id=pid;
  update public.payroll_periods set status='locked' where id=pid;
  blocked:=false;
  begin perform public.adjust_payroll_entry(peid,1,'[]'); exception when raise_exception then blocked:=true; end;
  assert blocked,'Locked entry cannot change';
  assert (select total_net from public.payroll_periods where id=pid)=5400000,'Failed adjustment rolls back totals';
  perform set_config('request.jwt.claims','{"sub":"bb000000-0000-4000-8000-000000000012","role":"authenticated"}',true);
  assert (select count(*) from public.payroll_entries)=1,'Employee can read own released entry';
  assert (select count(*) from public.payroll_periods)=0,'Employee cannot read company payroll totals';
  assert (select count(*) from public.my_payroll_periods())=1,'Employee receives own slip period';
  blocked:=false;
  begin insert into public.leave_requests(company_id,employee_id,request_type,start_date,end_date,reason,status) values(cid,eid,'Cuti','2099-01-01','2099-01-02','TEST','approved'); exception when insufficient_privilege then blocked:=true; end;
  assert blocked,'Employee cannot self-approve';
  insert into public.leave_requests(company_id,employee_id,request_type,start_date,end_date,reason) values(cid,eid,'Cuti','2099-01-01','2099-01-02','TEST');
  assert (select count(*) from public.leave_requests where employee_id=eid and status='submitted')=1,'Employee can submit request';
  perform public.cancel_request('leave_requests',(select id from public.leave_requests where employee_id=eid and status='submitted' limit 1));
  assert (select count(*) from public.leave_requests where employee_id=eid and status='cancelled')=1,'Employee can cancel submitted request';
  insert into public.leave_requests(company_id,employee_id,request_type,start_date,end_date,reason) values(cid,eid,'Cuti','2099-02-01','2099-02-02','TEST REVIEW');
  perform set_config('request.jwt.claims','{"sub":"bb000000-0000-4000-8000-000000000011","role":"authenticated"}',true);
  perform public.review_request('leave_requests',(select id from public.leave_requests where employee_id=eid and status='submitted' limit 1),'approved','TEST OK');
  assert (select count(*) from public.leave_requests where employee_id=eid and status='approved' and reviewer_note='TEST OK')=1,'HR approval must be atomic';
  assert (select count(*) from public.companies where id='bb000000-0000-4000-8000-000000000002')=0,'Other company must remain invisible';
  perform set_config('request.jwt.claims','{"sub":"bb000000-0000-4000-8000-000000000012","role":"authenticated"}',true);
  blocked:=false;
  begin perform public.save_employee(body,eid,stamp); exception when raise_exception then blocked:=true; end;
  assert blocked,'Employee cannot edit HR master';
end $$;
select 'PASS: draft, resume, schedule, stale edits, payroll calculation, effective dates, overlap, adjustment, locking, self-service, tenant isolation' as result;
rollback;
