import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Bell, CalendarCheck, ChevronRight, CircleDollarSign, ClipboardCheck, FileText, LayoutDashboard, LogOut, MapPin, Menu, Plus, Settings, ShieldCheck, Users, X } from 'lucide-react'
import { supabase } from './lib/supabase'
import './App.css'

type Profile = { id:string; company_id:string; full_name:string; username:string; role:string }
type Employee = { id:string; employee_code:string; full_name:string; department?:string|null; position?:string|null; base_salary:number; is_active:boolean }
const roles:Record<string,string>={owner:'Owner',hr_admin:'HR / Admin',finance:'Keuangan',supervisor:'Atasan',employee:'Karyawan'}
const money=(n:number)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n||0)
const today=new Date().toISOString().slice(0,10)

export default function App(){
  const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[page,setPage]=useState('Beranda'),[menu,setMenu]=useState(false),[loading,setLoading]=useState(true)
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>data.subscription.unsubscribe()},[])
  useEffect(()=>{if(!session?.user)return; supabase.from('profiles').select('*').eq('id',session.user.id).single().then(({data})=>setProfile(data as Profile|null))},[session])
  if(loading)return <Boot text="Menyiapkan ruang kerja…"/>; if(!session)return <Auth/>; if(!profile)return <Boot text="Memuat profil perusahaan…"/>;
  return <Shell profile={profile} page={page} setPage={setPage} menu={menu} setMenu={setMenu}/>
}

function Brand({small=false}:{small?:boolean}){return <div className={`brand ${small?'brand-small':''}`}><img src="https://raw.githubusercontent.com/hudbrother62-coder/bantu-beres-gajian-pro/main/public/bantu-beres-logo-transparent.png" alt="Bantu Beres"/><span>Gajian <b>Pro</b></span></div>}
function Boot({text}:{text:string}){return <main className="boot"><Brand/><p>{text}</p></main>}

function Auth(){
  const [register,setRegister]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const f=new FormData(e.currentTarget),id=String(f.get('identity')||'').trim().toLowerCase(),email=id.includes('@')?id:`${id}@team.bantuberes.local`;const {error}=await supabase.auth.signInWithPassword({email,password:String(f.get('password'))});setBusy(false);if(error)setMessage('Akun atau password belum tepat.')}
  const signup=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setMessage('');const data=Object.fromEntries(new FormData(e.currentTarget).entries()),{data:result,error}=await supabase.functions.invoke('register-owner',{body:data});if(error||result?.error){setBusy(false);setMessage(result?.error||'Pendaftaran belum dapat diproses.');return}const {error:loginError}=await supabase.auth.signInWithPassword({email:String(data.email),password:String(data.password)});setBusy(false);if(loginError)setMessage('Akun dibuat. Silakan masuk kembali.')}
  return <main className="auth"><section className="auth-story"><Brand/><p className="eyebrow">Payroll yang rapi, kerja lebih tenang</p><h1>Gaji selesai tanpa repot.</h1><p>Presensi, pengajuan, payroll, dan slip gaji dalam satu ruang kerja perusahaan.</p><ul><li><ShieldCheck/> Akses tim sesuai peran</li><li><ClipboardCheck/> Payroll dikunci setelah disetujui</li><li><FileText/> Laporan rapi dan siap unduh</li></ul></section><section className="auth-form"><div className="auth-card"><div className="tabs"><button className={!register?'active':''} onClick={()=>setRegister(false)}>Masuk</button><button className={register?'active':''} onClick={()=>setRegister(true)}>Daftar Owner</button></div>{register?<form onSubmit={signup} className="form"><Field label="Nama usaha"><input name="companyName" required placeholder="Contoh: Bintang Jaya"/></Field><div className="two"><Field label="Nama Owner"><input name="fullName" required/></Field><Field label="Username"><input name="username" minLength={4} required/></Field></div><Field label="Email Owner"><input name="email" type="email" required/></Field><Field label="Password"><input name="password" type="password" minLength={8} required/></Field><button className="button primary" disabled={busy}>{busy?'Membuat workspace…':'Buat workspace perusahaan'}<ChevronRight/></button></form>:<form onSubmit={login} className="form"><Field label="Email Owner atau username tim"><input name="identity" required placeholder="nama@usaha.com atau adminusaha"/></Field><Field label="Password"><input name="password" type="password" minLength={8} required/></Field><button className="button primary" disabled={busy}>{busy?'Memproses…':'Masuk ke workspace'}<ChevronRight/></button></form>}{message&&<p className="note">{message}</p>}<small>Tim dibuat langsung oleh Owner dari dalam workspace.</small></div></section></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}

function Shell({profile,page,setPage,menu,setMenu}:{profile:Profile;page:string;setPage:(p:string)=>void;menu:boolean;setMenu:(v:boolean)=>void}){
  const nav:[string,React.ElementType][]=[['Beranda',LayoutDashboard],['Karyawan',Users],['Kehadiran',CalendarCheck],['Payroll',CircleDollarSign],['Approval',ClipboardCheck],['Tim',ShieldCheck],['Laporan',FileText],['Pengaturan',Settings]]
  const pick=(name:string)=>{setPage(name);setMenu(false)}
  return <div className="shell"><aside className={`side ${menu?'shown':''}`}><div className="side-head"><Brand/><button className="icon mobile" onClick={()=>setMenu(false)}><X/></button></div><nav>{nav.map(([name,Icon])=><button key={name} className={page===name?'selected':''} onClick={()=>pick(name)}><Icon/><span>{name}</span></button>)}</nav><div className="who"><div className="avatar">{profile.full_name[0]}</div><div><b>{profile.full_name}</b><small>{roles[profile.role]}</small></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/></button></div></aside>{menu&&<button className="scrim" onClick={()=>setMenu(false)}/>}<main className="main"><header><button className="icon mobile" onClick={()=>setMenu(true)}><Menu/></button><div><p className="breadcrumb">Bantu Beres Gajian Pro</p><h2>{page}</h2></div><div className="header-end"><button className="icon"><Bell/></button><div className="avatar mini">{profile.full_name[0]}</div></div></header><Content page={page} profile={profile}/></main><nav className="bottom">{nav.slice(0,5).map(([name,Icon])=><button key={name} className={page===name?'selected':''} onClick={()=>pick(name)}><Icon/><span>{name}</span></button>)}</nav></div>
}

function Content({page,profile}:{page:string;profile:Profile}){if(page==='Beranda')return <Dashboard profile={profile}/>;if(page==='Karyawan')return <Employees profile={profile}/>;if(page==='Kehadiran')return <Attendance profile={profile}/>;if(page==='Payroll')return <Payroll profile={profile}/>;if(page==='Tim')return <Team profile={profile}/>;if(page==='Laporan')return <Reports/>;if(page==='Pengaturan')return <SettingsPage profile={profile}/>;return <Simple title="Approval" text="Izin, cuti, lembur, kasbon, dan reimburse akan muncul dalam satu antrean persetujuan."/>}
function Intro({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Empty({text}:{text:string}){return <div className="empty"><ClipboardCheck/><p>{text}</p></div>}
function Simple({title,text}:{title:string;text:string}){return <section className="page"><Intro eyebrow="Pusat tindakan" title={title} text={text}/><div className="card"><Empty text="Belum ada data yang perlu diproses."/></div></section>}

function Dashboard({profile}:{profile:Profile}){const [stats,setStats]=useState({employees:0,present:0,waiting:0,payroll:0});const [company,setCompany]=useState('Workspace Perusahaan');useEffect(()=>{void(async()=>{const [a,b,c,d,e,f,g]=await Promise.all([supabase.from('employees').select('*',{count:'exact',head:true}).eq('is_active',true),supabase.from('attendance_records').select('*',{count:'exact',head:true}).eq('attendance_date',today),supabase.from('leave_requests').select('*',{count:'exact',head:true}).eq('status','submitted'),supabase.from('overtime_requests').select('*',{count:'exact',head:true}).eq('status','submitted'),supabase.from('cash_advances').select('*',{count:'exact',head:true}).eq('status','submitted'),supabase.from('payroll_periods').select('total_net').in('status',['draft','review']).limit(1),supabase.from('companies').select('name').eq('id',profile.company_id).single()]);setCompany(g.data?.name||'Workspace Perusahaan');setStats({employees:a.count||0,present:b.count||0,waiting:(c.count||0)+(d.count||0)+(e.count||0),payroll:Number(f.data?.[0]?.total_net||0)})})},[profile.company_id]);return <section className="page"><div className="welcome"><div><p className="eyebrow">{company}</p><h1>Halo, {profile.full_name.split(' ')[0]}.</h1><p>Berikut hal penting yang perlu dibereskan hari ini.</p></div><span className="date"><CalendarCheck/>{new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span></div><div className="stats"><Stat icon={<Users/>} label="Karyawan aktif" value={String(stats.employees)} tone="purple"/><Stat icon={<MapPin/>} label="Sudah presensi" value={`${stats.present} hari ini`} tone="blue"/><Stat icon={<ClipboardCheck/>} label="Menunggu approval" value={String(stats.waiting)} tone="amber"/><Stat icon={<CircleDollarSign/>} label="Payroll berjalan" value={money(stats.payroll)} tone="green"/></div><div className="cols"><article className="card action"><div className="card-title"><div><p className="eyebrow">Prioritas</p><h3>Selesaikan payroll periode ini</h3></div><span className="badge draft">Draft</span></div><p>Periksa presensi, lembur, kasbon, dan reimburse sebelum payroll dikunci.</p><div className="progress"><i/></div><small>Langkah berikutnya: cek data karyawan</small></article><article className="card"><div className="card-title"><div><p className="eyebrow">Pusat approval</p><h3>Pengajuan terbaru</h3></div><span className="badge">{stats.waiting} menunggu</span></div><Empty text="Pengajuan dari tim akan muncul di sini."/></article></div></section>}
function Stat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string;tone:string}){return <article className="stat"><span className={tone}>{icon}</span><div><p>{label}</p><b>{value}</b></div></article>}

function Employees({profile}:{profile:Profile}){const [rows,setRows]=useState<Employee[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState('');const load=()=>supabase.from('employees').select('*').order('full_name').then(({data})=>setRows((data||[])as Employee[]));useEffect(()=>{void load()},[]);const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.from('employees').insert({company_id:profile.company_id,employee_code:String(f.get('code')),full_name:String(f.get('name')),department:String(f.get('department'))||null,position:String(f.get('position'))||null,base_salary:Number(f.get('salary')||0)});if(error)setMessage('Data belum tersimpan. Pastikan kode karyawan belum digunakan.');else{setMessage('Karyawan berhasil ditambahkan.');setOpen(false);void load()}};return <section className="page"><Intro eyebrow="Data master" title="Karyawan" text="Simpan data karyawan, jabatan, dan gaji pokok sebagai dasar payroll." action={<button className="button primary" onClick={()=>setOpen(true)}><Plus/>Tambah karyawan</button>}/>{message&&<p className="note">{message}</p>}<div className="card table"><table><thead><tr><th>Karyawan</th><th>Divisi</th><th>Jabatan</th><th>Gaji pokok</th><th>Status</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><b>{r.full_name}</b><small>{r.employee_code}</small></td><td>{r.department||'—'}</td><td>{r.position||'—'}</td><td>{money(Number(r.base_salary))}</td><td><span className="badge active">{r.is_active?'Aktif':'Nonaktif'}</span></td></tr>)}</tbody></table>{!rows.length&&<Empty text="Belum ada data karyawan. Tambahkan data pertama untuk mulai mengatur presensi dan payroll."/>}</div>{open&&<Modal title="Tambah karyawan" close={()=>setOpen(false)}><form onSubmit={add} className="form"><div className="two"><Field label="Kode karyawan"><input name="code" required placeholder="EMP-001"/></Field><Field label="Nama lengkap"><input name="name" required/></Field></div><div className="two"><Field label="Divisi"><input name="department"/></Field><Field label="Jabatan"><input name="position"/></Field></div><Field label="Gaji pokok"><input name="salary" type="number" min="0"/></Field><button className="button primary">Simpan karyawan</button></form></Modal>}</section>}

function Attendance({profile}:{profile:Profile}){const [employees,setEmployees]=useState<Employee[]>([]),[rows,setRows]=useState<any[]>([]),[message,setMessage]=useState('');const load=()=>Promise.all([supabase.from('employees').select('*').eq('is_active',true).order('full_name'),supabase.from('attendance_records').select('*, employees(full_name,employee_code)').eq('attendance_date',today)]).then(([a,b])=>{setEmployees((a.data||[])as Employee[]);setRows(b.data||[])});useEffect(()=>{void load()},[]);const mark=async(id:string)=>{const {error}=await supabase.from('attendance_records').insert({company_id:profile.company_id,employee_id:id,attendance_date:today,status:'present',check_in_at:new Date().toISOString(),location_note:'Dicatat oleh admin'});setMessage(error?'Presensi sudah tercatat atau belum dapat disimpan.':'Presensi berhasil dicatat.');if(!error)void load()};const marked=new Set(rows.map(x=>x.employee_id));return <section className="page"><Intro eyebrow="Kehadiran" title="Presensi hari ini" text="Pantau presensi dari kantor maupun lokasi kerja."/>{message&&<p className="note">{message}</p>}<div className="cols"><article className="card"><div className="card-title"><h3>Belum dicatat</h3><span className="badge">{employees.filter(x=>!marked.has(x.id)).length} orang</span></div>{employees.filter(x=>!marked.has(x.id)).map(e=><div className="row" key={e.id}><div className="avatar mini">{e.full_name[0]}</div><div><b>{e.full_name}</b><small>{e.position||e.department||'Karyawan'}</small></div><button className="button secondary" onClick={()=>mark(e.id)}>Hadir</button></div>)}{!employees.length&&<Empty text="Tambahkan karyawan terlebih dahulu."/>}</article><article className="card"><div className="card-title"><h3>Masuk hari ini</h3><span className="badge active">{rows.length} hadir</span></div>{rows.map(r=><div className="row" key={r.id}><i className="dot"/><div><b>{r.employees?.full_name||'Karyawan'}</b><small>{r.check_in_at?new Date(r.check_in_at).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):'Belum check-in'}</small></div><span className="badge active">Hadir</span></div>)}{!rows.length&&<Empty text="Belum ada presensi hari ini."/>}</article></div></section>}

function Payroll({profile}:{profile:Profile}){const [periods,setPeriods]=useState<any[]>([]),[message,setMessage]=useState('');const load=()=>supabase.from('payroll_periods').select('*').order('period_end',{ascending:false}).then(({data})=>setPeriods(data||[]));useEffect(()=>{void load()},[]);const create=async()=>{const n=new Date(),start=new Date(n.getFullYear(),n.getMonth(),1).toISOString().slice(0,10),end=new Date(n.getFullYear(),n.getMonth()+1,0).toISOString().slice(0,10);if(periods.some(x=>x.period_start===start)){setMessage('Payroll bulan ini sudah dibuat.');return}const {data:emps}=await supabase.from('employees').select('*').eq('is_active',true),total=(emps||[]).reduce((s:number,x:any)=>s+Number(x.base_salary||0),0);const {data:period,error}=await supabase.from('payroll_periods').insert({company_id:profile.company_id,period_start:start,period_end:end,payment_date:end,total_gross:total,total_net:total}).select('*').single();if(error||!period){setMessage('Payroll belum dapat dibuat.');return}if(emps?.length)await supabase.from('payroll_entries').insert(emps.map((e:any)=>({company_id:profile.company_id,payroll_period_id:period.id,employee_id:e.id,base_salary:e.base_salary,net_pay:e.base_salary})));setMessage('Draft payroll dibuat dari gaji pokok karyawan aktif.');void load()};return <section className="page"><Intro eyebrow="Penggajian" title="Payroll" text="Buat draft, periksa data, setujui, lalu kunci payroll." action={<button className="button primary" onClick={create}><Plus/>Buat payroll bulan ini</button>}/>{message&&<p className="note">{message}</p>}<div className="card table"><table><thead><tr><th>Periode</th><th>Tanggal bayar</th><th>Total bersih</th><th>Status</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td><b>{new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(new Date(`${p.period_start}T00:00:00`))}</b><small>{p.period_start} s.d. {p.period_end}</small></td><td>{p.payment_date||'—'}</td><td>{money(Number(p.total_net))}</td><td><span className="badge draft">{p.status}</span></td></tr>)}</tbody></table>{!periods.length&&<Empty text="Belum ada payroll. Mulai dengan membuat draft periode bulan ini."/>}</div><div className="notice"><ShieldCheck/><div><b>Payroll aman setelah dikunci</b><p>Periode final tidak berubah tanpa persetujuan Owner.</p></div></div></section>}

function Team({profile}:{profile:Profile}){const [rows,setRows]=useState<Profile[]>([]),[open,setOpen]=useState(false),[message,setMessage]=useState('');const load=()=>supabase.from('profiles').select('*').order('created_at').then(({data})=>setRows((data||[])as Profile[]));useEffect(()=>{void load()},[]);const add=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const {data,error}=await supabase.functions.invoke('create-team-member',{body:Object.fromEntries(new FormData(e.currentTarget).entries())});if(error||data?.error)setMessage(data?.error||'Akun tim belum dapat dibuat.');else{setMessage('Akun tim berhasil dibuat dan langsung masuk ke workspace ini.');setOpen(false);void load()}};return <section className="page"><Intro eyebrow="Akses perusahaan" title="Tim" text="Semua anggota masuk ke perusahaan Owner yang sama." action={profile.role==='owner'?<button className="button primary" onClick={()=>setOpen(true)}><Plus/>Tambah tim</button>:undefined}/>{message&&<p className="note">{message}</p>}<div className="team">{rows.map(r=><article className="card member" key={r.id}><div className="avatar">{r.full_name[0]}</div><div><h3>{r.full_name}</h3><p>@{r.username}</p><span className="badge">{roles[r.role]}</span></div></article>)}</div>{open&&<Modal title="Tambah anggota tim" close={()=>setOpen(false)}><form onSubmit={add} className="form"><div className="two"><Field label="Nama lengkap"><input name="fullName" required/></Field><Field label="Jabatan"><input name="jobTitle"/></Field></div><div className="two"><Field label="Username"><input name="username" minLength={4} required/></Field><Field label="Password awal"><input name="password" type="password" minLength={8} required/></Field></div><Field label="Role"><select name="role"><option value="hr_admin">HR / Admin</option><option value="finance">Keuangan</option><option value="supervisor">Atasan</option><option value="employee">Karyawan</option></select></Field><button className="button primary">Buat akun tim</button></form></Modal>}</section>}
function Reports(){const download=async()=>{const {data}=await supabase.from('employees').select('employee_code,full_name,department,position,base_salary,is_active').order('full_name');const header='Kode,Nama,Divisi,Jabatan,Gaji Pokok,Status',lines=(data||[]).map((r:any)=>[r.employee_code,r.full_name,r.department||'',r.position||'',r.base_salary,r.is_active?'Aktif':'Nonaktif'].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','));const blob=new Blob([[header,...lines].join('\n')],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='data-karyawan.csv';a.click();URL.revokeObjectURL(a.href)};return <section className="page"><Intro eyebrow="Rekap dan ekspor" title="Laporan" text="Unduh data yang dibutuhkan Owner, HR, dan Keuangan."/><div className="reports"><article className="card"><FileText/><h3>Data karyawan</h3><p>Daftar aktif, jabatan, divisi, dan gaji pokok.</p><button className="button secondary" onClick={download}>Unduh CSV</button></article><article className="card"><CircleDollarSign/><h3>Payroll bulanan</h3><p>Ringkasan periode dan total gaji.</p><button className="button secondary" disabled>Segera tersedia</button></article><article className="card"><CalendarCheck/><h3>Presensi</h3><p>Rekap kehadiran dan keterlambatan.</p><button className="button secondary" disabled>Segera tersedia</button></article></div></section>}
function SettingsPage({profile}:{profile:Profile}){const [company,setCompany]=useState<any>(null);useEffect(()=>{supabase.from('companies').select('*').eq('id',profile.company_id).single().then(({data})=>setCompany(data))},[profile.company_id]);return <section className="page"><Intro eyebrow="Konfigurasi" title="Pengaturan perusahaan" text="Identitas usaha dan dasar periode payroll."/><div className="cols"><article className="card"><h3>Perusahaan</h3><dl><dt>Nama workspace</dt><dd>{company?.name||'Memuat…'}</dd><dt>Hari payroll</dt><dd>Tanggal {company?.payroll_day||25} setiap bulan</dd><dt>Zona waktu</dt><dd>{company?.timezone||'Asia/Jakarta'}</dd></dl></article><article className="card"><h3>Keamanan data</h3><p>Data perusahaan dipisahkan dan role diperiksa langsung di database.</p><div className="check"><ShieldCheck/>RLS aktif untuk seluruh tabel payroll</div><div className="check"><ClipboardCheck/>Audit log disiapkan untuk tindakan penting</div></article></div></section>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-layer"><button className="backdrop" onClick={close}/><section className="modal"><header><h3>{title}</h3><button className="icon" onClick={close}><X/></button></header>{children}</section></div>}
