import { useMemo, useState } from 'react'
import { BookOpen, CheckCircle2, FileSpreadsheet, Lightbulb, Search, ShieldCheck } from 'lucide-react'
import './guide.css'

type Profile={role:string}
const roleName:Record<string,string>={owner:'Owner',hr_admin:'HR / Admin',finance:'Keuangan',supervisor:'Atasan',employee:'Karyawan'}

type Guide={title:string;audience:string;summary:string;steps:string[];tips?:string[]}
const guides:Guide[]=[
 {title:'Mulai menggunakan workspace',audience:'Semua role',summary:'Urutan awal agar data tidak saling terputus.',steps:['Owner melengkapi Pengaturan perusahaan lebih dulu.','HR/Admin menyiapkan Jadwal & Lokasi sebelum mengaktifkan data karyawan.','Masukkan data karyawan manual atau melalui Import Excel.','Hubungkan karyawan ke akun Tim/ESS bila karyawan perlu login sendiri.','Baru lanjutkan presensi, pengajuan, payroll, dan laporan.'],tips:['Jangan membuat akun ESS terpisah untuk orang yang sudah terhubung ke akun lain.','Data master karyawan menjadi sumber identitas utama untuk presensi dan payroll.']},
 {title:'Data Karyawan & Import Excel',audience:'Owner · HR/Admin',summary:'Cara input massal tanpa mengacak struktur data.',steps:['Buka menu Karyawan lalu tekan Unduh template Excel.','Isi sheet DATA_KARYAWAN tanpa mengubah nama header.','Nama Jadwal Kerja, Lokasi Kantor, Username Atasan, dan Username Akun ESS harus cocok dengan data yang sudah ada di web.','Upload melalui tombol Import Excel. Sistem memvalidasi seluruh baris lebih dulu.','Jika ada kesalahan, perbaiki file sampai status validasi bersih lalu tekan Import.'],tips:['ID Karyawan wajib unik.','Gunakan Status Import = Draft bila data organisasi/jadwal belum lengkap.','Username Akun ESS bersifat opsional dan hanya untuk akun Tim yang belum terhubung.']},
 {title:'Tim & akun ESS',audience:'Owner · HR/Admin',summary:'Akun login harus tetap terhubung ke data karyawan yang benar.',steps:['Buka menu Tim untuk melihat status hubungan Karyawan ↔ Akun Tim.','Saat membuat akun baru, pilih karyawan yang sudah ada agar tidak membuat data ganda.','Jika belum ada karyawan, role Karyawan dapat dibuat sebagai draft lalu dilengkapi dari menu Karyawan.','Akun lama yang belum terhubung dapat dipasangkan dari menu Tim.'],tips:['Satu karyawan hanya boleh memiliki satu akun ESS.','Nonaktifkan akun jika akses harus dihentikan tanpa menghapus histori.']},
 {title:'Kehadiran',audience:'Owner · HR/Admin · Atasan · Karyawan',summary:'Presensi mengikuti identitas karyawan dan aturan lokasi/jadwal.',steps:['Karyawan melakukan check-in/check-out dari menu Kehadiran.','Owner/HR memantau presensi harian dan rekap bulanan.','Atasan dapat memantau tim sesuai kewenangannya.','Periksa status terlambat, izin, sakit, alfa, dan catatan lokasi sebelum menutup periode.'],tips:['Pastikan karyawan aktif memiliki jadwal kerja.','Jangan mengubah identitas karyawan setelah histori presensi terbentuk kecuali memang diperlukan.']},
 {title:'Pengajuan & Approval',audience:'Semua role sesuai kewenangan',summary:'Cuti, lembur, kasbon, dan reimburse memakai alur persetujuan.',steps:['Karyawan membuat pengajuan dari menu Pengajuan.','Atasan/HR/Keuangan memeriksa sesuai jenis dan kewenangan.','Aksi setujui, tolak, atau batalkan selalu perlu konfirmasi.','Status hasil persetujuan akan menjadi bagian laporan periode.'],tips:['Periksa tanggal, nominal, dan alasan sebelum menyetujui.','Hindari memproses tombol berulang; sistem menampilkan status proses otomatis.']},
 {title:'Payroll',audience:'Owner · HR/Admin · Keuangan',summary:'Payroll diproses bertahap agar perubahan dapat diaudit.',steps:['Pastikan data karyawan, gaji pokok, presensi, dan pengajuan periode sudah benar.','Buat/generate payroll untuk periode yang dipilih.','Review rincian bruto, pendapatan, potongan, dan net pay.','Setujui lalu kunci payroll jika sudah final.','Tandai dibayar setelah pembayaran benar-benar dilakukan.'],tips:['Jangan mengunci payroll sebelum koreksi selesai.','Slip karyawan sebaiknya dibuka setelah periode terkunci/dibayar.']},
 {title:'Laporan perusahaan',audience:'Owner · HR/Admin · Keuangan',summary:'Gunakan laporan sebagai dokumen operasional, bukan screenshot dashboard.',steps:['Pilih jenis laporan dan periode.','Review ringkasan manajemen dan tabel detail.','Gunakan PDF/Cetak untuk dokumen final.','Gunakan Word Editable untuk revisi dokumen.','Gunakan CSV untuk analisis lanjutan di spreadsheet.'],tips:['Verifikasi data sumber sebelum menandatangani laporan.','Perhatikan catatan otomatis tentang keterlambatan, alfa, pengajuan pending, dan payroll belum final.']},
 {title:'Aturan data & keamanan',audience:'Semua role',summary:'Prinsip utama agar histori perusahaan tetap aman.',steps:['Gunakan hak akses sesuai role.','Jangan berbagi password akun antar orang.','Nonaktifkan akun yang tidak digunakan daripada menghapus histori penting.','Gunakan tombol Hapus hanya untuk data yang memang salah dan belum memiliki histori.','Logout setelah menggunakan perangkat bersama.'],tips:['Konfirmasi tindakan sensitif ditampilkan sebelum eksekusi.','Jika proses sedang berjalan, tunggu indikator selesai agar tidak terjadi permintaan ganda.']},
]

export function GuideManagement({profile}:{profile:Profile}){
 const [query,setQuery]=useState('')
 const visible=useMemo(()=>guides.filter(g=>`${g.title} ${g.audience} ${g.summary} ${g.steps.join(' ')} ${g.tips?.join(' ')||''}`.toLowerCase().includes(query.toLowerCase())),[query])
 return <section className="page guide-page">
  <div className="guide-hero"><div><p className="eyebrow">Buku panduan</p><h1>Panduan Gajian Pro</h1><p>Tutorial penggunaan, urutan kerja, tips, dan aturan operasional agar data tetap rapi.</p></div><div className="guide-role"><ShieldCheck/><span>Akses Anda</span><b>{roleName[profile.role]||profile.role}</b></div></div>
  <label className="guide-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cari panduan: payroll, import, presensi…"/></label>
  <article className="guide-start card"><div className="guide-icon"><BookOpen/></div><div><h2>Alur penggunaan yang disarankan</h2><p>Pengaturan perusahaan → Jadwal & Lokasi → Karyawan → Tim/ESS → Kehadiran & Pengajuan → Payroll → Laporan.</p></div></article>
  <div className="guide-grid">{visible.map((guide,index)=><article className="card guide-card" key={guide.title}><header><span className="guide-number">{String(index+1).padStart(2,'0')}</span><div><h3>{guide.title}</h3><small>{guide.audience}</small></div></header><p>{guide.summary}</p><ol>{guide.steps.map(step=><li key={step}><CheckCircle2/>{step}</li>)}</ol>{guide.tips&&<div className="guide-tips"><div><Lightbulb/>Tips</div>{guide.tips.map(tip=><p key={tip}>{tip}</p>)}</div>}</article>)}</div>
  {!visible.length&&<div className="card guide-empty"><FileSpreadsheet/><p>Panduan tidak ditemukan. Coba kata kunci lain.</p></div>}
 </section>
}
