import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { supabase } from './lib/supabase'

type Row = Record<string, any>
type Profile = { id: string; company_id: string; role: string }
const money = (n: number) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n || 0)
const statusText: Record<string, string> = { draft: 'Draft', review: 'Dalam review', approved: 'Disetujui', locked: 'Dikunci', paid: 'Dibayar' }
const monthDates = () => { const n = new Date(); const month = `${n.getFullYear()}-${String(n.getMonth() + 1).padStart(2, '0')}`; return { start: `${month}-01`, end: `${month}-${new Date(n.getFullYear(), n.getMonth() + 1, 0).getDate()}` } }
export function PayrollWorkflow({ profile }: { profile: Profile }) {
  const manage = ['owner', 'hr_admin', 'finance'].includes(profile.role)
  const [periods, setPeriods] = useState<Row[]>([]), [entries, setEntries] = useState<Row[]>([]), [period, setPeriod] = useState<Row | null>(null)
  const [message, setMessage] = useState(''), [busy, setBusy] = useState(false), [form, setForm] = useState<Row | null>(null), [entry, setEntry] = useState<Row | null>(null), [slip, setSlip] = useState<Row | null>(null)
  const load = useCallback(async () => { const result = manage ? await supabase.from('payroll_periods').select('*').order('period_start', { ascending: false }) : await supabase.rpc('my_payroll_periods'); if (result.error) setMessage('Periode payroll belum berhasil dimuat.'); else { const data=(result.data || []) as Row[]; setPeriods(data); setPeriod(current => current ? data.find((p:Row) => p.id === current.id) || null : null) } }, [manage])
  useEffect(() => { void load() }, [load])
  const openPeriod = async (p: Row) => { setBusy(true); const result = await supabase.from('payroll_entries').select('*').eq('payroll_period_id', p.id).order('created_at'); setBusy(false); if (result.error) { setMessage('Rincian payroll belum dapat dimuat.'); return } setPeriod(p); setEntries(result.data || []) }
  const generate = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); if (!form || busy) return; setBusy(true); const f = new FormData(e.currentTarget); const result = await supabase.rpc('generate_payroll', { p_start: f.get('start'), p_end: f.get('end'), p_payment: f.get('payment'), p_period: form.id || null }); setBusy(false); if (result.error) { setMessage(result.error.message); return } setMessage('Draft payroll dan seluruh rinciannya berhasil disimpan.'); setForm(null); setPeriod(null); setEntries([]); await load() }
  const move = async (p: Row, next: string) => { setBusy(true); const result = await supabase.from('payroll_periods').update({ status: next }).eq('id', p.id).eq('status', p.status).select('*').single(); setBusy(false); if (result.error) { setMessage(result.error.message); return } setMessage(`Status payroll: ${statusText[next]}.`); await load(); if (period?.id === p.id) setPeriod(result.data) }
  const removeDraft = async (p:Row) => { if(p.status!=='draft'||!confirm(`Hapus draft payroll ${p.period_start} — ${p.period_end}?`)) return; setBusy(true); const {error}=await supabase.rpc('delete_payroll_draft',{p_period:p.id}); setBusy(false); setMessage(error?error.message:'Draft payroll berhasil dihapus.'); if(!error){ if(period?.id===p.id){setPeriod(null);setEntries([])} await load() } }
  const adjust = async (e: FormEvent) => { e.preventDefault(); if (!entry) return; setBusy(true); const result = await supabase.rpc('adjust_payroll_entry', { p_entry: entry.id, p_base: Number(entry.base_salary), p_details: entry.detail }); setBusy(false); if (result.error) { setMessage(result.error.message); return } setEntry(null); setMessage('Rincian dan total payroll diperbarui.'); await load(); if (period) await openPeriod(period) }
  const exportPeriod = () => { if (!period) return; const cells = (v: unknown) => `"${String(v ?? '').replace(/^[=+@\-\t\r]/, "'$&").replaceAll('"', '""')}"`; const lines = [['Kode', 'Nama', 'Gaji pokok', 'Tunjangan', 'Potongan', 'Gaji bersih', 'Bank', 'Nomor rekening'], ...entries.map(e => [e.employee_snapshot?.employee_code, e.employee_snapshot?.full_name, e.base_salary, e.earnings, e.deductions, e.net_pay, e.employee_snapshot?.bank_name, e.employee_snapshot?.bank_account_number])]; const url = URL.createObjectURL(new Blob(['\uFEFF' + lines.map(row => row.map(cells).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `payroll-${period.period_start}.csv`; a.click(); URL.revokeObjectURL(url) }
  const next: Record<string, [string, string]> = { draft: ['review', 'Ajukan review'], review: ['approved', 'Setujui'], approved: ['locked', 'Kunci payroll'], locked: ['paid', 'Tandai dibayar'] }
  return <section className="page"><div className="intro"><div><p className="eyebrow">Penggajian</p><h1>{manage ? 'Payroll' : 'Slip gaji saya'}</h1><p>{manage ? 'Periksa rincian sebelum menyetujui dan mengunci payroll.' : 'Slip tersedia setelah HR mengunci payroll.'}</p></div>{manage && <button className="button primary" disabled={busy} onClick={() => { const d = monthDates(); setForm({ start: d.start, end: d.end, payment: d.end }) }}>Buat payroll</button>}</div>
    {message && <p className="note" role="status">{message}</p>}
    <div className="card table"><table><thead><tr><th>Periode</th><th>Tanggal bayar</th>{manage && <th>Total bersih</th>}<th>Status</th><th>Aksi</th></tr></thead><tbody>{periods.map(p => <tr key={p.id}><td>{p.period_start} — {p.period_end}</td><td>{p.payment_date}</td>{manage && <td>{money(p.total_net)}</td>}<td>{statusText[p.status]}</td><td><button className="button secondary" disabled={busy} onClick={() => void openPeriod(p)}>{manage ? 'Rincian' : 'Buka slip'}</button>{manage && next[p.status] && <button className="button secondary" disabled={busy} onClick={() => void move(p, next[p.status][0])}>{next[p.status][1]}</button>}{manage&&p.status==='draft'&&<button className="button secondary" disabled={busy} onClick={()=>void removeDraft(p)}>Hapus</button>}</td></tr>)}</tbody></table>{!periods.length && <p className="empty">{manage ? 'Belum ada periode payroll.' : 'Belum ada slip gaji yang diterbitkan.'}</p>}</div>
    {period && <article className="card"><div className="card-title"><h3>Rincian {period.period_start} — {period.period_end}</h3><button className="button secondary" onClick={() => setPeriod(null)}>Tutup rincian</button></div><div className="workflow-actions">{manage && <button className="button secondary" onClick={exportPeriod}>Ekspor CSV</button>}{manage && period.status === 'draft' && <button className="button secondary" disabled={busy} onClick={() => setForm({ id: period.id, start: period.period_start, end: period.period_end, payment: period.payment_date })}>Edit / hitung ulang draft</button>}{manage && period.status === 'review' && <button className="button secondary" disabled={busy} onClick={() => void move(period, 'draft')}>Kembalikan ke draft</button>}</div><div className="table"><table><thead><tr><th>Karyawan</th><th>Pokok</th><th>Tunjangan</th><th>Potongan</th><th>Bersih</th><th>Aksi</th></tr></thead><tbody>{entries.map(e => <tr key={e.id}><td><b>{e.employee_snapshot?.full_name || 'Karyawan'}</b><small>{e.employee_snapshot?.employee_code}</small></td><td>{money(e.base_salary)}</td><td>{money(e.earnings)}</td><td>{money(e.deductions)}</td><td>{money(e.net_pay)}</td><td><button className="button secondary" onClick={() => setSlip(e)}>{['locked', 'paid'].includes(period.status) ? 'Slip gaji' : 'Pratinjau slip'}</button>{manage && period.status === 'draft' && <button className="button secondary" onClick={() => setEntry(structuredClone(e))}>Edit rincian</button>}</td></tr>)}</tbody></table></div>{!entries.length && <p className="note">Draft ini belum memiliki rincian. Pilih Hitung ulang draft setelah karyawan dilengkapi.</p>}</article>}
    {manage && <p className="note">Perhitungan mencakup gaji pokok dan komponen sesuai tanggal efektif. Pajak, BPJS, lembur, prorata, kasbon, dan reimburse perlu ditinjau serta dimasukkan sebagai penyesuaian. Menandai dibayar mencatat status pembayaran; tidak mentransfer uang.</p>}
    {form && <div className="modal-layer"><div className="backdrop" /><section className="modal" role="dialog" aria-modal="true" aria-label="Buat payroll"><header><h3>{form.id ? 'Edit / hitung ulang draft' : 'Buat payroll'}</h3><button className="button secondary" disabled={busy} onClick={() => setForm(null)}>Tutup</button></header>{form.id && <p className="note">Perhitungan ulang mengganti rincian dan penyesuaian draft dengan data karyawan serta komponen terbaru.</p>}<form className="form" onSubmit={generate}>{[['start', 'Mulai periode'], ['end', 'Akhir periode'], ['payment', 'Tanggal pembayaran']].map(([key, label]) => <label className="field" key={key}><span>{label}</span><input name={key} type="date" required defaultValue={form[key]} /></label>)}<button className="button primary" disabled={busy}>{busy ? 'Menghitung…' : 'Hitung dan simpan draft'}</button></form></section></div>}
    {entry && <div className="modal-layer"><div className="backdrop" /><section className="modal workflow-modal" role="dialog" aria-modal="true" aria-label="Edit rincian payroll"><header><h3>{entry.employee_snapshot?.full_name}</h3><button className="button secondary" disabled={busy} onClick={() => setEntry(null)}>Tutup</button></header><form className="form" onSubmit={adjust}><label className="field"><span>Gaji pokok periode ini</span><input type="number" min="0" required value={entry.base_salary} onChange={e => setEntry({ ...entry, base_salary: Number(e.target.value) })} /></label>{entry.detail.map((d: Row, i: number) => <div className="workflow-tools" key={i}><label className="field"><span>Nama komponen</span><input required value={d.name} onChange={e => setEntry({ ...entry, detail: entry.detail.map((x: Row, j: number) => i === j ? { ...x, name: e.target.value } : x) })} /></label><label className="field"><span>Jenis</span><select value={d.kind} onChange={e => setEntry({ ...entry, detail: entry.detail.map((x: Row, j: number) => i === j ? { ...x, kind: e.target.value } : x) })}><option value="earning">Pendapatan</option><option value="deduction">Potongan</option></select></label><label className="field"><span>Nominal</span><input type="number" min="0" required value={d.amount} onChange={e => setEntry({ ...entry, detail: entry.detail.map((x: Row, j: number) => i === j ? { ...x, amount: Number(e.target.value) } : x) })} /></label><button type="button" className="button secondary" onClick={() => setEntry({ ...entry, detail: entry.detail.filter((_: Row, j: number) => j !== i) })}>Hapus baris</button></div>)}<button type="button" className="button secondary" onClick={() => setEntry({ ...entry, detail: [...entry.detail, { name: '', kind: 'earning', amount: 0 }] })}>Tambah penyesuaian</button><button className="button primary" disabled={busy}>Simpan rincian dan total</button></form></section></div>}
    {slip && period && <div className="modal-layer"><div className="backdrop" /><section className="modal slip-print" role="dialog" aria-modal="true" aria-label="Slip gaji"><div className="no-print workflow-actions"><button className="button secondary" onClick={() => setSlip(null)}>Tutup slip</button><button className="button primary" onClick={() => window.print()}>Cetak / simpan PDF</button></div><p className="eyebrow">Bantu Beres Gajian Pro</p><h2>{['locked', 'paid'].includes(period.status) ? 'Slip gaji' : 'Draft slip gaji'}</h2><p>{period.period_start} — {period.period_end}</p><h3>{slip.employee_snapshot?.full_name}</h3><p>{slip.employee_snapshot?.employee_code} · {slip.employee_snapshot?.department}</p><dl><dt>Gaji pokok</dt><dd>{money(slip.base_salary)}</dd>{slip.detail.map((d: Row, i: number) => <div key={i}><dt>{d.name} ({d.kind === 'earning' ? 'Pendapatan' : 'Potongan'})</dt><dd>{money(d.amount)}</dd></div>)}<dt>Total bersih</dt><dd><strong>{money(slip.net_pay)}</strong></dd></dl><p>Tanggal pembayaran: {period.payment_date} · {statusText[period.status]}</p><p>Rekening: {slip.employee_snapshot?.bank_name || '—'} · {slip.employee_snapshot?.bank_account_number || '—'}</p></section></div>}
  </section>
}