import { useEffect, useMemo, useState } from 'react'
import { CalendarCheck, Check, ClipboardCheck, Clock3, MapPin, TrendingUp, UserCheck, Users, XCircle } from 'lucide-react'
import { supabase } from './lib/supabase'

type Profile={id:string;company_id:string;full_name:string;role:string}
type Employee={id:string;profile_id?:string|null;employee_code:string;full_name:string;department?:string|null;position?:string|null;is_active:boolean;supervisor_profile_id?:string|null}
type Attendance={id:string;employee_id:string;attendance_date:string;status:string;check_in_at?:string|null;check_out_at?:string|null;employees?:{full_name?:string|null;employee_code?:string|null}|null}
type RequestItem={id:string;table:'leave_requests'|'overtime_requests';kind:string;employee_id:string;employee:string;detail:string;status:string;created:string}

const localDate=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const monthNow=()=>localDate().slice(0,7)
const statusLabel=(status:string)=>({present:'Hadir',late:'Terlambat',absent:'Alfa',leave:'Izin/Cuti',sick:'Sakit',holiday:'Libur'} as Record<string,string>)[status]||status
const fmtTime=(value?:string|null)=>value?new Date(value).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'}):'—'
const fmtDate=(value:string)=>new Date(`${value}T12:00:00`).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})

function Empty({text}:{text:string}){return <div className="empty"><ClipboardCheck/><p>{text}</p></div>}
function Intro({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="intro"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Stat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string;tone:string}){return <article className="stat"><span className={tone}>{icon}</span><div><p>{label}</p><b>{value}</b></div></article>}

async function loadTeam(profileId:string){
  const {data,error}=await supabase.from('employees').select('id,profile_id,employee_code,full_name,department,position,is_active,supervisor_profile_id').eq('supervisor_profile_id',profileId).eq('is_active',true).order('full_name')
  if(error)throw error
  return (data||[]) as Employee[]
}

async function loadTeamRequests(teamIds:string[]){
  if(!teamIds.length)return [] as RequestItem[]
  const [leave,overtime]=await Promise.all([
    supabase.from('leave_requests').select('id,employee_id,start_date,end_date,reason,status,created_at,employees(full_name)').in('employee_id',teamIds).order('created_at',{ascending:false}),
    supabase.from('overtime_requests').select('id,employee_id,overtime_date,start_time,end_time,reason,status,created_at,employees(full_name)').in('employee_id',teamIds).order('created_at',{ascending:false}),
  ])
  const rows:RequestItem[]=[
    ...(leave.data||[]).map((x:any)=>({id:x.id,table:'leave_requests' as const,kind:'Cuti / izin',employee_id:x.employee_id,employee:x.employees?.full_name||'Karyawan',detail:`${fmtDate(x.start_date)} s.d. ${fmtDate(x.end_date)}${x.reason?` · ${x.reason}`:''}`,status:x.status,created:x.created_at})),
    ...(overtime.data||[]).map((x:any)=>({id:x.id,table:'overtime_requests' as const,kind:'Lembur',employee_id:x.employee_id,employee:x.employees?.full_name||'Karyawan',detail:`${fmtDate(x.overtime_date)} · ${String(x.start_time).slice(0,5)}–${String(x.end_time).slice(0,5)}${x.reason?` · ${x.reason}`:''}`,status:x.status,created:x.created_at})),
  ]
  return rows.sort((a,b)=>b.created.localeCompare(a.created))
}

export function SupervisorDashboard({profile}:{profile:Profile}){
  const [team,setTeam]=useState<Employee[]>([]),[attendance,setAttendance]=useState<Attendance[]>([]),[requests,setRequests]=useState<RequestItem[]>([]),[loading,setLoading]=useState(true)
  useEffect(()=>{void(async()=>{try{const members=await loadTeam(profile.id);setTeam(members);const ids=members.map(x=>x.id);const [attendanceResult,requestRows]=await Promise.all([ids.length?supabase.from('attendance_records').select('id,employee_id,attendance_date,status,check_in_at,check_out_at,employees(full_name,employee_code)').eq('attendance_date',localDate()).in('employee_id',ids):Promise.resolve({data:[],error:null}),loadTeamRequests(ids)]);setAttendance((attendanceResult.data||[]) as Attendance[]);setRequests(requestRows)}finally{setLoading(false)}})()},[profile.id])
  const pending=requests.filter(x=>x.status==='submitted')
  const present=attendance.filter(x=>x.status==='present'||x.status==='late').length
  const absent=Math.max(team.length-present,0)
  return <section className="page"><div className="welcome"><div><p className="eyebrow">Workspace Atasan</p><h1>Halo, {profile.full_name.split(' ')[0]}.</h1><p>Pantau tim, kehadiran, dan approval yang membutuhkan keputusan Anda.</p></div><span className="date"><CalendarCheck/>{new Intl.DateTimeFormat('id-ID',{weekday:'long',day:'numeric',month:'long'}).format(new Date())}</span></div><div className="stats"><Stat icon={<Users/>} label="Anggota tim" value={String(team.length)} tone="purple"/><Stat icon={<UserCheck/>} label="Hadir hari ini" value={String(present)} tone="blue"/><Stat icon={<Clock3/>} label="Belum presensi" value={String(absent)} tone="amber"/><Stat icon={<ClipboardCheck/>} label="Menunggu approval" value={String(pending.length)} tone="green"/></div><div className="cols"><article className="card"><div className="card-title"><div><p className="eyebrow">Kehadiran tim</p><h3>Status hari ini</h3></div><span className="badge active">{present}/{team.length} hadir</span></div>{team.slice(0,6).map(member=>{const row=attendance.find(x=>x.employee_id===member.id);return <div className="row" key={member.id}><div className="avatar mini">{member.full_name[0]}</div><div><b>{member.full_name}</b><small>{member.position||member.department||'Karyawan'}{row?.check_in_at?` · masuk ${fmtTime(row.check_in_at)}`:''}</small></div><span className={`badge ${row&&(row.status==='present'||row.status==='late')?'active':'draft'}`}>{row?statusLabel(row.status):'Belum presensi'}</span></div>})}{!team.length&&<Empty text={loading?'Memuat anggota tim…':'Belum ada karyawan yang ditetapkan ke Atasan ini. Owner/HR dapat memilih Atasan Langsung pada data karyawan.'}/>}</article><article className="card"><div className="card-title"><div><p className="eyebrow">Pusat approval</p><h3>Pengajuan tim terbaru</h3></div><span className="badge">{pending.length} menunggu</span></div>{pending.slice(0,5).map(item=><div className="row" key={`${item.table}-${item.id}`}><ClipboardCheck/><div><b>{item.employee}</b><small>{item.kind} · {item.detail}</small></div><span className="badge draft">Menunggu</span></div>)}{!pending.length&&<Empty text="Tidak ada cuti/izin atau lembur anggota tim yang menunggu approval."/>}</article></div></section>
}

export function SupervisorTeam({profile}:{profile:Profile}){
  const [team,setTeam]=useState<Employee[]>([]),[loading,setLoading]=useState(true)
  useEffect(()=>{loadTeam(profile.id).then(setTeam).finally(()=>setLoading(false))},[profile.id])
  return <section className="page"><Intro eyebrow="Pengawasan langsung" title="Tim Saya" text="Hanya karyawan yang ditetapkan kepada Anda sebagai Atasan Langsung yang tampil di sini."/><div className="team">{team.map(member=><article className="card member" key={member.id}><div className="avatar">{member.full_name[0]}</div><div><h3>{member.full_name}</h3><p>{member.employee_code}</p><div className="inline-actions"><span className="badge active">Aktif</span>{member.department&&<span className="badge">{member.department}</span>}</div><small>{member.position||'Jabatan belum diisi'}</small></div></article>)}{!team.length&&<article className="card"><Empty text={loading?'Memuat tim…':'Belum ada anggota tim. Owner/HR perlu memilih Atasan Langsung pada menu Karyawan.'}/></article>}</div></section>
}

export function SupervisorAttendance({profile}:{profile:Profile}){
  const [date,setDate]=useState(localDate()),[team,setTeam]=useState<Employee[]>([]),[rows,setRows]=useState<Attendance[]>([]),[self,setSelf]=useState<Employee|null>(null),[message,setMessage]=useState(''),[locating,setLocating]=useState(false)
  const load=async()=>{const [members,selfResult]=await Promise.all([loadTeam(profile.id),supabase.from('employees').select('id,profile_id,employee_code,full_name,department,position,is_active,supervisor_profile_id').eq('profile_id',profile.id).eq('is_active',true).maybeSingle()]);setTeam(members);setSelf((selfResult.data||null) as Employee|null);const ids=members.map(x=>x.id);if(!ids.length){setRows([]);return}const {data}=await supabase.from('attendance_records').select('id,employee_id,attendance_date,status,check_in_at,check_out_at,employees(full_name,employee_code)').eq('attendance_date',date).in('employee_id',ids);setRows((data||[]) as Attendance[])}
  useEffect(()=>{void load()},[profile.id,date])
  const checkIn=()=>{if(!self){setMessage('Akun Atasan belum terhubung ke data karyawan aktif.');return}if(date!==localDate()){setMessage('Check-in hanya dapat dilakukan untuk hari ini.');return}if(!navigator.geolocation){setMessage('Perangkat ini tidak menyediakan lokasi.');return}setLocating(true);navigator.geolocation.getCurrentPosition(async pos=>{const {data,error}=await supabase.rpc('attendance_check_in_self',{p_latitude:pos.coords.latitude,p_longitude:pos.coords.longitude,p_accuracy_m:pos.coords.accuracy});setLocating(false);setMessage(error?error.message:`Check-in berhasil · ${data?.location||'lokasi kerja'} · jarak ${data?.distance_m??0} m.`)},()=>{setLocating(false);setMessage('Lokasi tidak diizinkan. Aktifkan izin lokasi untuk check-in.')},{enableHighAccuracy:true,timeout:12000,maximumAge:15000})}
  return <section className="page"><Intro eyebrow="Kehadiran tim" title="Kehadiran Tim" text="Pantau status presensi anggota tim per tanggal. Atasan tetap dapat melakukan check-in dirinya sendiri." action={<div className="inline-actions"><label className="field"><span>Tanggal</span><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{date===localDate()&&<button className="button primary" onClick={checkIn} disabled={locating}><MapPin/>{locating?'Mencari lokasi…':'Check-in saya'}</button>}</div>}/>{message&&<p className="note">{message}</p>}<div className="card table"><table><thead><tr><th>Karyawan</th><th>Status</th><th>Masuk</th><th>Keluar</th></tr></thead><tbody>{team.map(member=>{const row=rows.find(x=>x.employee_id===member.id);return <tr key={member.id}><td><b>{member.full_name}</b><small>{member.employee_code} · {member.position||member.department||'Karyawan'}</small></td><td><span className={`badge ${row&&(row.status==='present'||row.status==='late')?'active':'draft'}`}>{row?statusLabel(row.status):'Belum presensi'}</span></td><td>{fmtTime(row?.check_in_at)}</td><td>{fmtTime(row?.check_out_at)}</td></tr>})}</tbody></table>{!team.length&&<Empty text="Belum ada anggota tim yang ditetapkan kepada Anda."/>}</div></section>
}

export function SupervisorApprovals({profile}:{profile:Profile}){
  const [items,setItems]=useState<RequestItem[]>([]),[filter,setFilter]=useState('Menunggu'),[message,setMessage]=useState(''),[busy,setBusy]=useState('')
  const load=async()=>{const team=await loadTeam(profile.id);setItems(await loadTeamRequests(team.map(x=>x.id)))}
  useEffect(()=>{void load()},[profile.id])
  const review=async(item:RequestItem,status:'approved'|'rejected')=>{setBusy(item.id);const {error}=await supabase.rpc('review_request',{p_table:item.table,p_id:item.id,p_status:status,p_note:null});setBusy('');setMessage(error?error.message:`Pengajuan ${status==='approved'?'disetujui':'ditolak'}.`);if(!error)await load()}
  const visible=items.filter(item=>filter==='Semua'||(filter==='Menunggu'?item.status==='submitted':filter==='Disetujui'?item.status==='approved':item.status==='rejected'))
  return <section className="page"><Intro eyebrow="Keputusan Atasan" title="Approval Tim" text="Atasan hanya memproses cuti/izin dan lembur dari anggota tim langsung. Kasbon, reimburse, payroll, dan keuangan tetap ditangani role terkait."/>{message&&<p className="note">{message}</p>}<div className="filters">{['Menunggu','Disetujui','Ditolak','Semua'].map(x=><button key={x} className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x}</button>)}</div><div className="approval-list">{visible.map(item=><article className="card approval-item" key={`${item.table}-${item.id}`}><div className="approval-icon"><ClipboardCheck/></div><div className="approval-copy"><div className="approval-top"><span className="badge">{item.kind}</span><span className={`badge ${item.status==='approved'?'active':item.status==='rejected'?'rejected':'draft'}`}>{item.status}</span></div><h3>{item.employee}</h3><p>{item.detail}</p><small>Diajukan {new Date(item.created).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}</small></div>{item.status==='submitted'&&<div className="approval-actions"><button className="button secondary" disabled={busy===item.id} onClick={()=>void review(item,'rejected')}><XCircle/>Tolak</button><button className="button primary" disabled={busy===item.id} onClick={()=>void review(item,'approved')}><Check/>Setujui</button></div>}</article>)}{!visible.length&&<div className="card"><Empty text="Belum ada pengajuan anggota tim pada filter ini."/></div>}</div></section>
}

export function SupervisorReport({profile}:{profile:Profile}){
  const [month,setMonth]=useState(monthNow()),[team,setTeam]=useState<Employee[]>([]),[rows,setRows]=useState<Attendance[]>([])
  useEffect(()=>{void(async()=>{const members=await loadTeam(profile.id);setTeam(members);const ids=members.map(x=>x.id);if(!ids.length){setRows([]);return}const [year,mon]=month.split('-').map(Number),start=`${month}-01`,last=new Date(year,mon,0).getDate(),end=`${month}-${String(last).padStart(2,'0')}`;const {data}=await supabase.from('attendance_records').select('id,employee_id,attendance_date,status,check_in_at,check_out_at').in('employee_id',ids).gte('attendance_date',start).lte('attendance_date',end);setRows((data||[]) as Attendance[])})()},[profile.id,month])
  const stats=useMemo(()=>team.map(member=>{const mine=rows.filter(x=>x.employee_id===member.id),present=mine.filter(x=>x.status==='present'||x.status==='late').length,late=mine.filter(x=>x.status==='late').length;return {member,total:mine.length,present,late,percent:mine.length?Math.round(present/mine.length*100):0}}),[team,rows])
  const total=rows.length,present=rows.filter(x=>x.status==='present'||x.status==='late').length,percent=total?Math.round(present/total*100):0
  return <section className="page"><Intro eyebrow="Rekap tim" title="Rekap Tim" text="Ringkasan kehadiran anggota tim untuk periode bulanan." action={<label className="field"><span>Bulan</span><input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label>}/><div className="stats"><Stat icon={<Users/>} label="Anggota tim" value={String(team.length)} tone="purple"/><Stat icon={<CalendarCheck/>} label="Presensi tercatat" value={String(total)} tone="blue"/><Stat icon={<UserCheck/>} label="Hadir" value={String(present)} tone="green"/><Stat icon={<TrendingUp/>} label="Rata-rata hadir" value={`${percent}%`} tone="amber"/></div><div className="card table" style={{marginTop:17}}><table><thead><tr><th>Karyawan</th><th>Hari tercatat</th><th>Hadir</th><th>Terlambat</th><th>Kehadiran</th></tr></thead><tbody>{stats.map(item=><tr key={item.member.id}><td><b>{item.member.full_name}</b><small>{item.member.position||item.member.department||'Karyawan'}</small></td><td>{item.total}</td><td>{item.present}</td><td>{item.late}</td><td><span className={`badge ${item.percent>=90?'active':'draft'}`}>{item.total?`${item.percent}%`:'—'}</span></td></tr>)}</tbody></table>{!team.length&&<Empty text="Belum ada anggota tim untuk direkap."/>}</div></section>
}
